version: 2

jobs:
  build:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    working_directory: /tmp/simple_workflow
    steps:
      - restore_cache:
          keys:
            - docker-v1
          paths:
            - /home/circleci/docker/cache.tar
            - /home/circleci/.apt-cache
      - checkout
      - run:
          name: create/save docker image
          no_output_timeout: 60m
          command: |
            echo "export USER=$(whoami)" >> $HOME/.circlerc
            source $HOME/.circlerc
            mkdir -p $HOME/docker
            if [[ -e "$HOME/docker/cache.tar" ]]; then 
              docker load --input $HOME/docker/cache.tar
            fi
            docker images
            /tmp/simple_workflow/Simple_Prep_docker jessie 20170410T000000Z
            repronimtag=repronim:$(docker images repronim | tail -n 1 | awk '{print $2}')
            echo "export repronimtag=$repronimtag" >> $HOME/.circlerc
            echo $repronimtag
            docker save -o $HOME/docker/cache.tar $repronimtag

      - save_cache:
         key: docker-v1
         paths:
            - /home/circleci/docker/cache.tar
            - /home/circleci/.apt-cache

      - run:
          name: test outputs
          no_output_timeout: 60m
          command: |
            source $HOME/.circlerc
            echo $repronimtag
            mkdir -p $HOME/output
            docker run -it --rm -v $HOME/output:/opt/repronim/simple_workflow/scripts/output $repronimtag run_demo_workflow.py --key 11an55u9t2TAf0EV2pHN0vOd8Ww2Gie-tHp9xGULh_dA -n 2
            docker run -it --rm -v $HOME/output:/opt/repronim/simple_workflow/scripts/output $repronimtag check_output.py --ignoremissing | tee $HOME/log.txt
            cat $HOME/log.txt && if grep -q "MATCH" $HOME/log.txt; then true; else false; fi

      - store_artifacts:
          path: /home/circleci/log.txt
      - store_artifacts:
          path: /home/circleci/output/ActualOutput.csv
      - store_artifacts:
          path: /home/circleci/output/Difference.csv
      - store_artifacts:
          path: /home/circleci/output/ExpectedOutput.csv

workflows:
    version: 2
    simple_ci:
        jobs:
          - build